### ISSUE TITLE
Segmentation Violation when running Platform in Kubernetes

### ISSUE THREAD

**Issue by namanrawal47** [opentdf/charts#30]
<img width="1119" alt="image" src="https://github.com/opentdf/charts/assets/57806571/16916657-121d-47d6-831e-e5afcaee28b9">

I've added a screenshot of the platform container logs after adding kas secrets, enabling the playground, and running the following on Minikube:
```
helm install -f values.yaml opentdf .
```

OS: Ubuntu 22.04.4 LTS
Version: Jammy Jellyfish
Docker Version: Docker Engine - Community v 25.0.5
Helm Version: v3.14.3
Kubectl Version: Client Version = v1.29.3 && Server Version = v.1.28.3
Minikube Version: v.1.32.0

`platform-db` and `platform-keycloak` are both up and running with no errors. `opentdf-platform` is in a CrashLoopBackOff state. Kubernetes storage provisioner is running fine. No other errors to note. 

Please assist! I am getting the feeling this has to do with an application-specific bug. Thank you.

**Comment by namanrawal47** [comment]
Please include Paul Flynn in this discussion if possible. We (BAH) met with him yesterday and had possibly related errors when running decryption in Docker-Compose.

**Comment by strantalis** [comment]
@namanrawal47 There is a bug in the nightly build of the platform after some changes related to restructuring how the database client was handled.

As a temporary solution you can disable the health checks. Not ideal but quickest option to get around this issue.

https://github.com/opentdf/charts/blob/31926cc2dc284f1d2572a8bbf30dbadfe3ff8fa6/charts/platform/values.yaml#L162

This issue gives some details https://github.com/opentdf/platform/issues/700

**Comment by namanrawal47** [comment]
Thank you - this is working now.

**Comment by strantalis** [comment]
This should be resolved by https://github.com/opentdf/platform/pull/755
